- name: Create Log Rotate File 
  template: src=mongoc.logrotate.j2 dest=/etc/logrotate.d/mongos-mongo.log mode=0640

- name: Create Data, Log Directory 
  file: path={{item}} owner={{os_usert}} group={{os_group}} mode=0755 state=directory 
  with_items: 
    - "{{mongos_data_dir}}" 
    - "{{mongos_log_dir}}"

- name: Copy Config File 
  template: src=mongos.conf.j2 dest={{mongo_bin_dir}}/conf/{{mongos_conf_file_name}} owner={{os_user}} group={{os_group}} mode=0640

- name: Copy Secret Key File
  copy: src=files/mongo.key dest={{mongo_bin_dir}}/conf/mongos.key owner={{os_user}} group={{os_group}} mode=0400

- name: Copy Startup/Shutdown Script 
  template: src={{item}} dest={{mongo_bin_dir}}/{{item}} owner={{os_user}} group={{os_group}} mode=0740 
  with_items: 
    - "startup_mongos.sh" 
    - "shutdown_mongos.sh"

- name: Check MongoDB Daemon 
  shell: "ps -ef | grep {{mongos_conf_file_name}} | grep -v grep | wc -l" 
  register: check_mongodb_daemon

- set_fact: 
    mongodb_daemon: "{{ check_mongodb_daemon['stdout'] }}" 
  ignore_errors: yes 

- name: MongoDB Start_1(Apply Config File) 
  command: "/bin/su - mongo -c \"{{mongo_bin_dir}}/bin/mongos -f {{mongo_bin_dir}}/conf/{{mongos_conf_file_name}}\"" 
  when: mongodb_daemon == '0" 
  ignore_errors: yes

- name: Copy Add Shard Script
  template: src=mongos.addshard.j2 dest={{mongo_bin_dir}}/mongos_addShard.sh owner={{os_user}} group={{os_group}} mode=0740

- name: Add Shard
  command: "/bin/su - mongo -c \"{{mongo_bin_dir}}/bin/mongosh -f localhost:{{mongos_port}} -u {{mongo_admin}} -p {{mongo_admin_pw}} {{mongo_bin_dir}}/mongos_addShard.sh\""

- name: Remove Init File 
  shell: "rm -rf {{mongo_bin_dir}}/mongos_addShard.sh" 

