- name: Create Log Rotate File 
  template: src=mongoc.logrotate.j2 dest=/etc/logrotate.d/mongoc-mongo.log mode=0640

- name: Create Data, Log Directory 
  file: path={{item}} owner={{os_usert}} group={{os_group}} mode=0755 state=directory 
  with_items: 
    - "{{mongoc_data_dir}}" 
    - "{{mongoc_log_dir}}"

- name: Copy Config File 
  template: src=mongoc.conf.j2 dest={{mongo_bin_dir}}/conf/{{mongoc_conf_file_name}} owner={{os_user}} group={{os_group}} mode=0640

- name: Copy Startup/Shutdown Script 
  template: src={{item}} dest={{mongo_bin_dir}}/{{item}} owner={{os_user}} group={{os_group}} mode=0740 
  with_items: 
    - "startup_mongoc.sh" 
    - "shutdown_mongoc.sh"

- name: Check MongoDB Daemon 
  shell: "ps -ef | grep {{mongoc_conf_file_name}} | grep -v grep | wc -l" 
  register: check_mongodb_daemon

- set_fact: 
    mongodb_daemon: "{{ check_mongodb_daemon['stdout'] }}" 
  ignore_errors: yes 

- name: MongoDB Start_1(Apply Config File) 
  command: "/bin/su - mongo -c \"{{mongo_bin_dir}}/bin/mongod -f {{mongo_bin_dir}}/conf/{{mongoc_conf_file_name}}\"" 
  when: mongodb_daemon == '0" 
  ignore_errors: yes

- name: Copy Create User File
  template: src=mongoc.user.j2 dest={{mongo_bin_dir}}/mongoc_user.sh owner={{os_user}} group={{os_group}} mode=0740

- name: Create DB User
  command: "/bin/su - mongo -c \"sh {{mongo_bin_dir}}/mongoc_user.sh\"

- name: Shutdown MongoDB
  command: "/bin/su - mongo -c \"{{mongo_bin_dir}}/bin/mongod -f {{mongo_bin_dir}}/conf/{{mongoc_conf_file_name}} --shutdown\""

- name: Modify Config File(Replica)
  lineinfile:
    path: "{{mongo_bin_dirt}}/conf/{{mongoc_conf_file_name}}"
    line: "replication:\n enableMajorityReadConcern: true\n   replSetName : \"configRs\"

- name: Copy Secret Key File
  copy: src=files/mongo.key dest={{mongo_bin_dir}}/conf/mongoc.key owner={{os_user}} group={{os_group}} mode=0400

- name: Modify Config File(Secret Key)
  lineinfile:
    path: "{{mongo_bin_dir}}/conf/{{mongoc_conf_file_name}}"
    line: "\nsecurity:\n   authorization: enabled\n   clusterAuthMode: keyFile\n   keyFile: {{mongo_bin_dir}}/conf/mongoc.key"

- name: Modify Config File(Shard)
  lineinfile:
    path: "{{mongo_bin_dir}}/conf/{{mongoc_conf_file_name}}"
    line: "\nsharding:\n   clusterRole: \"configsvr\""

- name: MongoDB Start_2(Apply Replica, Secret Key, Shard)
  command: "/bin/su - mongo -c \"{{mongo_bin_dir}}/bin/mongod -f {{mongo_bin_dir}}/conf/{{mongoc_conf_file_name}}\""

- name: Copy Replica Set Init File(Only Primary)
  template: src=mongoc.repl.j2 dest={{mongo_bin_dir}}/mongoc_repl.j2 owner={{os_user}} group={{os_group}} mode=0740
  when: inventory_hostname.endswith('1') 

- name: Check Replica Set(Only Primary) 
  command: "/bin/su - mongo -c \"{{mongo_bin_dir}}/bin/mongosh localhost:{{mongoc_port}} -u {{mongo_admin}} -p {{mongo_admin_pw}} --eval 'rs.status();'\""
  ignore_errors: yes 
  register: check_repl_status 

- name: Replica Set Initiate(Only Primary) 
  command: "/bin/su - mongo -c \"{{mongo_bin_dir}}/bin/mongosh localhost:{{mongoc_port}} -u {{mongo_admin}} -p {{mongo_admin_pw}} {{mongo_bin_dir}}/mongoc.repl.j2\""
  when: 
    - inventory_hostname.endswith('1') 
    - check_repl_status is failed 

- name: Remove Init File 
  shell: "rm -rf {{mongo_bin_dir}}/mongoc_*" 

